# Generated by Django 5.0.1 on 2024-01-11 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='split_details',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
