# Generated by Django 5.0.1 on 2024-01-11 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_balance_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='split_details',
            new_name='shares',
        ),
        migrations.RenameField(
            model_name='expense',
            old_name='type',
            new_name='split_type',
        ),
        migrations.AddField(
            model_name='expense',
            name='images',
            field=models.ImageField(blank=True, upload_to='expense_images'),
        ),
        migrations.AddField(
            model_name='expense',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='expense',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
