# Generated by Django 5.0.1 on 2024-01-11 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_split_details_expense_shares_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='shares',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
